apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  EUREKA_SERVER_URL: "http://eureka:8761/eureka"
  KAFKA_BOOTSTRAP_SERVERS: "kafka-service:9092"
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  POSTGRES_HOST: "postgres-service"
  POSTGRES_PORT: "5432"
