spring.application.name=authservice

server.port=8085

eureka.client.service-url.defaultZone=http://eureka:8761/eureka
eureka.instance.prefer-ip-address=true

spring.datasource.url=jdbc:postgresql://host.docker.internal:5432/authdb
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=myverysecretkeymyverysecretkeymyverysecretkey
jwt.expiration=3600000

gateway.secret=my-gateway-secret

management.tracing.sampling.probability=1.0
management.zipkin.tracing.endpoint=http://zipkin:9411/api/v2/spans

oauth2.google.client-id=${GOOGLE_CLIENT_ID:google-client-id}
oauth2.google.client-secret=${GOOGLE_CLIENT_SECRET:google-client-secret}
oauth2.github.client-id=${GITHUB_CLIENT_ID:github-client-id}
oauth2.github.client-secret=${GITHUB_CLIENT_SECRET:github-client-secret}

